### PR TITLE
fingerprint feature added

### PR DESCRIPTION
**Pull request by Shahzadah**
Finger print feature is added as - If app is logged in then it requires fingerprint validation by showing new screen.

### CODE REVIEW

**Comment by sloppycoder** [comment]
In the existing navigation structure, the job of that screen is check the existence of userToken then decide which screen to go next. Instead of creating a new screen for FingerPrint login, can we move this logic into AuthLoadScreening?

btw, have you tested this on Android? I think on Android the FingerPrint API requires some UI components to work too.

**Comment by Shahzadah** [comment]
Yes, We can easily move this logic to AuthLoadScreen. 
Regarding testing on Android - Yes, I have tested on Android and it worked fine.

**Comment by sloppycoder** [comment]
can you move the logic into AuthLoading and remove FingerPrint screen?
One more thing, you could add logic to check if FingerPrint is available, 2 reasons:
1. some devices maybe too old and doesn't have a finger printer reader
2. some users never use that feature even when the device supports it.

thanks.

**Comment by Shahzadah** [comment]
Sure. Will do this.

Just one question, What would be the action if FingerPrint not available?

**Comment by sloppycoder** [comment]
If fingerprint is not available on the device, or no finger is registered, or user cancel the authentication prompt, the app should drop back to login screen. 

this is the normal behaviour for other apps like mobile banking etc.

**Comment by Shahzadah** [comment]
I have moved the fingerprint logic into AuthLoading and removed FingerPrint screen.
Also, applied logic to check Fingerprint hardware availability and not enrolled status - Based on that showing fingerprint option or launching login screen. 

Thanks

**Comment by sloppycoder** [comment]
It mostly works, but there're 2 problems:

1. on iOS, when the prompt for Touch ID comes up, if I click cancel, it just says "Authentication failed" and then pop the same Touch ID window again. This is not the correct behaviour. normally when user cancels the Touch ID, the app should allow user to login manually (ie. username/password). For this app, it should just display the "Log Me In" button.

2. The MainNavigator still refers to FingerPrintScreen. I guess you forgot to commit the updated file? This sort of error happens way too often unfortunately, I think we can solve it by adding a simple test case that loads the screen. The test case will fail if there is compilation errors, thus prevent bad code from being committed. Can you try to implement a simple test case?

Thanks.

**Comment by Shahzadah** [comment]
1. For cancel action - As of now, I have followed that If fingerprint hardware available and is enrolled, then its mandatory to authenticate via fingerprint. 
Now, I will change it as - If user click cancel, It should redirect to login screen.

2. Regarding MainNavigator - Commit was fine but I missed to remove the line for FingerPrintScreen, However functionality was taken care and there was no compilation issue and tested on Android(both devices - With FingerPrint hardware and without) and iPhone also.

**Comment by Shahzadah** [comment]
I have incorporated the feedback as - on iOS, when user click cancel on touch prompt dialog. It is getting redirected to login screen.

Thanks.

**Pull request merged**
